### ISSUE TITLE
Suggestion: Execute Sync Commands from Bungeecord Console

### ISSUE THREAD

**Issue by wm-b** [SawFowl/CommandSync#11]
Would it be at all possible to have this plugin execute commands on servers from the proxy?

If you're wondering why I want to do this, I'm trying to set up a bungeecord-side custom command that executes a bungeecord command AND spigot-server side command using MyCommand for BungeeCord.

If this plugin were able to send commands to spigot servers from the bungeecord console it would be the missing piece of the puzzle. ^^

**Comment by SawFowl** [comment]
For the proxy server, the `proxysync` command has been added. The functionality is similar to the `sync` command.
