### ISSUE TITLE
Not working on bungee server

### ISSUE THREAD

**Issue by Greazi-Times** [SawFowl/CommandSync#13]
I have setup every thing as said only when useing /sync console all bc test1234
there is no broadcast on the servers
how can I fix this?
Also I have [Thread-15/INFO]: Could not connect to the server.
I don't know if this is a ropert of the plugin?

**Comment by djohts** [comment]
Try setting server IP on all back-end servers (Bukkit-powered) to public IPv4, so if your Bungeecord server IP is 125.89.20.42, put this IP on every Bukkit server.
