### ISSUE TITLE
Can you make the Papi variable take effect in the instruction

### ISSUE THREAD

**Issue by axin0452** [SawFowl/CommandSync#15]
When the player executes /sync player eco give %player_name% 100 or  /sync console eco give %player_name% 100,
The feedback result is that the target account does not exist,
Make the Papi variable effective so that its instructions can be given to the player 100money normally,
Can you make the Papi variable take effect in the instruction.

**Comment by SawFowl** [comment]
The plugin is not intended to be used by players. It is for the administrator only. Use custom commands.
