### ISSUE TITLE
Commands are not connecting to bungeecord console

### ISSUE THREAD

**Issue by BakProject** [SawFowl/CommandSync#16]
Hey there! I have been running into some issues with trying to get the /sync command to work. I connected all backend servers to the bungeecord proxy IP and it was no longer saying "Can't connect to server" but I could still not run any commands. The command I was running was our broadcast which will run on all servers.

Works fine when typing normally but when I use the /sync command it says it runs but nothing happens, in-game or in console.

**Comment by SawFowl** [comment]
Check on the latest version of the plugin. If the problem repeats, create a new issue and specify the server/proxy/java versions used.
