### ISSUE TITLE
[Bug] Bungeecord Server error

### ISSUE THREAD

**Issue by Lennord** [SawFowl/CommandSync#22]
Hello, I installed the recent version (2.8.1) on my bungeecord server but an error appeared, I am using the latest version of bungeecord, so if you could take a look at the error.

Error:

`[WARNING] Exception encountered when loading plugin: CommandSync
java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
    at sawfowl.commandsyncserver.bungee.CSS.onEnable(CSS.java:51)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    ... 5 more`

**Comment by SawFowl** [comment]
What versions of java and bungeecord do you use?

**Comment by Lennord** [comment]
Bungeecord #1636.

Java 17.0.1

Link: https://ci.md-5.net/job/BungeeCord/1636/

**Comment by SawFowl** [comment]
Please show the output of the `java -version`

**Comment by Lennord** [comment]
I have jdk-17.0.1.

17:04:47 [INFO] Using standard Java JCE cipher.
17:04:47 [INFO] Using standard Java compressor.
17:04:47 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:862bb2a:1636
17:04:47 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())

17:04:47 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())

17:04:47 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())

17:04:47 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())

17:04:47 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())

17:04:47 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())

17:04:47 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
17:04:48 [INFO] Loaded plugin LuckPerms version 5.4.25 by Luck
17:04:48 [INFO] Loaded plugin cmd_find version git:cmd_find:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
17:04:48 [INFO] Loaded plugin CommandSync version 2.8.1 by YoFuzzy3
17:04:48 [INFO] Loaded plugin cmd_server version git:cmd_server:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
17:04:48 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
17:04:48 [INFO] Loaded plugin cmd_send version git:cmd_send:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
17:04:48 [INFO] Loaded plugin cmd_list version git:cmd_list:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
17:04:48 [WARNING] Forced host server pvp is not defined
17:04:48 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
17:04:48 [INFO]         __
17:04:48 [INFO]   |    |__)   LuckPerms v5.4.25
17:04:48 [INFO] [LuckPerms] Loading configuration...
17:04:48 [INFO]   |___ |      Running on BungeeCord - BungeeCord
17:04:48 [INFO]
17:04:48 [INFO] [LuckPerms] Loading storage provider... [H2]
17:04:48 [INFO] [LuckPerms] Loading internal permission managers...
17:04:48 [INFO] [LuckPerms] Performing initial data load...
17:04:48 [INFO] [LuckPerms] Successfully enabled. (took 732ms)
17:04:48 [INFO] Enabled plugin LuckPerms version 5.4.25 by Luck
17:04:48 [INFO] Enabled plugin cmd_find version git:cmd_find:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
17:04:48 [WARNING] Exception encountered when loading plugin: CommandSync
java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
    at sawfowl.commandsyncserver.bungee.CSS.onEnable(CSS.java:51)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    ... 5 more
17:04:48 [INFO] Enabled plugin cmd_server version git:cmd_server:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
17:04:48 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
17:04:48 [INFO] Enabled plugin cmd_send version git:cmd_send:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
17:04:48 [INFO] Enabled plugin cmd_list version git:cmd_list:1.18-R0.1-SNAPSHOT:862bb2a:1636 by SpigotMC
17:04:48 [INFO] Listening on /0.0.0.0:25565`

**Comment by SawFowl** [comment]
Use this proxy https://papermc.io/downloads#Waterfall
It supports all your plugins. BungeeCord is outdated and lacks some modern libraries.

**Comment by Lennord** [comment]
Ok thank you I will use it.

**Comment by Lennord** [comment]
It's ok, it works with Waterfall, thank you very much for your help.

Have a good day !
