### ISSUE TITLE
the use of a proxy causes CSC to jam the main thread

### ISSUE THREAD

**Issue by FallenCrystal** [SawFowl/CommandSync#28]
im not quite sure its a problem with proxy. 
but this happened after I installed "Clash-For-Windows"
for some reason i need to use a proxy to connect the high-speed internet. 
i'll go and try if v2ray will cause an error.

**Comment by SawFowl** [comment]
Perhaps the plugin can't figure out which address to use, try specifying an explicit address instead of a generic one.
