### ISSUE TITLE
constant attempts to connect to report.mcstats.org (on bungeecord)

### ISSUE THREAD

**Issue by FallenCrystal** [SawFowl/CommandSync#31]
![image](https://user-images.githubusercontent.com/71176602/211211700-81654d9f-4454-4175-80d9-7fdce737f1ff.png)
please explain what this is for. its consuming my network buffer

**Comment by SawFowl** [comment]
Collection of impersonal statistics on plugin usage.  But why this is added to the plugin you should ask its author, I just updated it to current versions of the game.
I didn't even improve the quality of the code, just fixed some bugs and implemented support for Sponge and Velocity.
