### ISSUE TITLE
Is this Safe?

### ISSUE THREAD

**Issue by SteveLinkNoah** [SawFowl/CommandSync#35]
Is this save to use on a Server with a Firewall(CommandSync port is disallowed) that only sends the Commands to other local servers? Because it cloudn't it be vulnerble to Brute Force?

**Comment by SawFowl** [comment]
Using a firewall is even desirable. It is only unnecessary if the plugin is running on localhost.

**Comment by SteveLinkNoah** [comment]
So in my case it is safe because it runs local and the port is disallowed?

**Comment by SawFowl** [comment]
Yes.
