### ISSUE TITLE
Velocity proxy support

### ISSUE THREAD

**Issue by LGCMcLovin** [SawFowl/CommandSync#4]
Would like to request added support for Velocity Proxy.

 Information about this proxy is available @ velocitypowered.com

**Comment by SawFowl** [comment]
Alas, I do not know the Velocity API. I'll leave it open, maybe I'll do it someday.

**Comment by zsn741656478** [comment]
We need it, too. Velocity is better than Bungee. :)

**Comment by ElTodoFull** [comment]
How is it going?

**Comment by SawFowl** [comment]
> How is it going?

Done. https://forums.papermc.io/threads/commandsync.314/
