### ISSUE TITLE
Big error

### ISSUE THREAD

**Issue by kb079** [SawFowl/CommandSync#5]
Hello, could you fix this, please?

" When you reboot one of your servers. It loaded all the plugins but then does not load commandsync it just says Enabled commandsync. To fix this is you have to reboot the bungee then it fixes it. Please fix this!! Thanks"

How to reproduce: I have bungee online, but I restarting one of my spigot servers, the spigot server is locked in loading CommandSync plugin and never start the server, so I need to remove the plugin to start my server.

Using WaterFall 1.14.4, last release and PaperSpigot 1.14.4 last release too.

**Comment by SawFowl** [comment]
I will check it out soon. I advise you to enable the function to delete the history of the entered commands.

**Comment by SawFowl** [comment]
I have not been able to catch this error. I will close the topic. If the problem occurs again, let me know.
