### ISSUE TITLE
Spigot Server Hanging on Start

### ISSUE THREAD

**Issue by Dakotaa** [SawFowl/CommandSync#6]
I've had this issue before, but it's happening again and seems to be happening consistently, every time this server is started. On start, when CommandSync loads and gets to this point:
>[02:00:26] [Server thread/INFO]: [CommandSync] Enabling CommandSync v2.5.3*
>[02:00:26] [Server thread/INFO]: Configuration file loaded.
nothing happens, and the server does not continue to start. It shows the login attempts of players, but nothing else. The only solution so far has been to restart the Bungeecord proxy. Once the proxy has restarted, the server continues to start normally.

I have removedata set to true for all servers and the proxy.

**Comment by SawFowl** [comment]
I will try to come up with something, but I do not promise anything, since I myself can't reproduce this problem.

**Comment by JasonHorkles** [comment]
I also have this problem almost every day now. It looks like this issue starts to happen after enough of these appear in console (which idk why that's even happening in the first place) but it requires the proxy to be restarted to fix the other servers not wanting to connect after they restart

```
>.... [10:59:35 INFO] [CommandSync]: Received new connection from [IP]
>.... [10:59:36 ERROR]: java.net.SocketException: Connection reset
>.... [10:59:36 ERROR]: at java.net.SocketInputStream.read(SocketInputStream.java:210)
>.... [10:59:36 ERROR]: at java.net.SocketInputStream.read(SocketInputStream.java:141)
>.... [10:59:36 ERROR]: at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
>.... [10:59:36 ERROR]: at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
>.... [10:59:36 ERROR]: at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
>.... [10:59:36 ERROR]: at java.io.InputStreamReader.read(InputStreamReader.java:184)
>.... [10:59:36 ERROR]: at java.io.BufferedReader.fill(BufferedReader.java:161)
>.... [10:59:36 ERROR]: at java.io.BufferedReader.readLine(BufferedReader.java:324)
>.... [10:59:36 ERROR]: at java.io.BufferedReader.readLine(BufferedReader.java:389)
>.... [10:59:36 ERROR]: at Mr_Krab.CommandSyncServer.Bungee.ClientHandler.<init>(ClientHandler.java:41)
>.... [10:59:36 ERROR]: at Mr_Krab.CommandSyncServer.Bungee.ClientListener.run(ClientListener.java:20)
```
and
```
>.... [10:59:09 INFO] [CommandSync]: Received new connection from [IP]
>.... [10:59:09 ERROR]: Exception in thread "Thread-25" java.lang.NullPointerException
>.... [10:59:09 ERROR]: at Mr_Krab.CommandSyncServer.Bungee.ClientHandler.<init>(ClientHandler.java:41)
>.... [10:59:09 ERROR]: at Mr_Krab.CommandSyncServer.Bungee.ClientListener.run(ClientListener.java:20)
```

**Comment by Etokura** [comment]
I have this same issue. The only fix is a bungee restart it seems - a bit of a problem when your entire network gets booted off every 24 hours.

[https://gyazo.com/a9ef913d9700b14d981438b2206d1773]Console Photo (Not Bungee)

The bungee console shows nothing. 
No ping, nothing.

Could it be from the differences in versions?
I'm running Bungee commandsync whilst running sponge commandsync for pixelmon.

**Comment by JasonHorkles** [comment]
> I have this same issue. The only fix is a bungee restart it seems - a bit of a problem when your entire network gets booted off every 24 hours.
> 
> [https://gyazo.com/a9ef913d9700b14d981438b2206d1773]Console Photo (Not Bungee)
> 
> The bungee console shows nothing. 
> No ping, nothing.
> 
> Could it be from the differences in versions?
> I'm running Bungee commandsync whilst running sponge commandsync for pixelmon.

I use the same jar on each server and the proxy and it still happens

**Comment by Etokura** [comment]
After checking through logs on the bungee I stumbled across something that might be of value here. 2 separate errors that are from commandsync at different intervals. I have no idea if it's related or not, but I'll post it here.

Error 1:

23:00:20 [INFO] Â§aReceived new connection from [ip hidden manually].
23:00:20 [SEVERE] java.net.SocketException: Connection reset
23:00:20 [SEVERE] 	at java.net.SocketInputStream.read(SocketInputStream.java:210)
23:00:20 [SEVERE] 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
23:00:20 [SEVERE] 	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
23:00:20 [SEVERE] 	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
23:00:20 [SEVERE] 	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
23:00:20 [SEVERE] 	at java.io.InputStreamReader.read(InputStreamReader.java:184)
23:00:20 [SEVERE] 	at java.io.BufferedReader.fill(BufferedReader.java:161)
23:00:20 [SEVERE] 	at java.io.BufferedReader.readLine(BufferedReader.java:324)
23:00:20 [SEVERE] 	at java.io.BufferedReader.readLine(BufferedReader.java:389)
23:00:20 [SEVERE] 	at Mr_Krab.CommandSyncServer.Bungee.ClientHandler.<init>(ClientHandler.java:45)
23:00:20 [SEVERE] 	at Mr_Krab.CommandSyncServer.Bungee.ClientListener.run(ClientListener.java:20)



Error 2:
11:42:02 [SEVERE] Exception in thread "Thread-30" 
11:42:02 [SEVERE] java.lang.NullPointerException
11:42:02 [SEVERE] 	at Mr_Krab.CommandSyncServer.Bungee.ClientHandler.<init>(ClientHandler.java:45)
11:42:02 [SEVERE] 	at Mr_Krab.CommandSyncServer.Bungee.ClientListener.run(ClientListener.java:20)


Additional information:
Changing the config file in any way (excluding IP or Port change) on the non bungee server yields no change. Even if the password is changed the server will still hang upon restart.

**Comment by Etokura** [comment]
> I use the same jar on each server and the proxy and it still happens

I was mistaken thinking mine were different versions, they are in fact the same between all my servers.

**Comment by Dakotaa** [comment]
It seems like this resource is dead - I stopped using it when this issue began back in March, and have since found a different plugin that functions pretty much the same.

[This plugin](https://www.spigotmc.org/resources/multichat-full-rgb-colour-support.26204/) allows you to run commands on different servers, as well as executing bungeecord commands. There's a bunch of other features that you probably don't want, and those can be disabled. I wrote a simple script with Skript to make a `/sync <servername/global> <command>` command, and it has worked perfectly for the last year. Only issue I've had with this system is that the commands that are sent to other servers don't run if there's no players on that server, and only execute once a player logs in, but this hasn't been too big of a problem.

**Comment by JasonHorkles** [comment]
> It seems like this resource is dead - I stopped using it when this issue began back in March, and have since found a different plugin that functions pretty much the same.
> 
> [This plugin](https://www.spigotmc.org/resources/multichat-full-rgb-colour-support.26204/) allows you to run commands on different servers, as well as executing bungeecord commands. There's a bunch of other features that you probably don't want, and those can be disabled. I wrote a simple script with Skript to make a `/sync <servername/global> <command>` command, and it has worked perfectly for the last year. Only issue I've had with this system is that the commands that are sent to other servers don't run if there's no players on that server, and only execute once a player logs in, but this hasn't been too big of a problem.

That's the problem with just using the bungee plugin messaging system - a player has to be online for it to run. With how I use commandsync I need it to work regardless of the players online unfortunately

**Comment by JasonHorkles** [comment]
Hey all, it appears the dev isn't going to fix the issue, so I decided to take this matter into my own hands. I've tweaked the plugin to have slightly more optimized code and those errors should also no longer appear. I've been using the plugin on my servers for a few days now and haven't seen the issue appear at all, whereas it would've appeared had I still been using the old jar.

You can download the updated jar [here](https://github.com/JasonHorkles/CommandSync/releases).
If you find any problems, let me know! :)

**Comment by SawFowl** [comment]
I have not been able to catch this error. I will close the topic. If the problem occurs again, let me know.
