### ISSUE TITLE
Russian symbols and letters 

### ISSUE THREAD

**Issue by AndryLavandery** [SawFowl/CommandSync#8]
I have an error, the russian letters and word do not are sent, and instead of them incomprehensible characters.
https://skr.sh/s2ewhPCLf4e

**Comment by SawFowl** [comment]
Start the server with the UTF-8 encoding flag.
И если что я русский. Юзать кодировку UTF-8 в общем надо и не юзать винду, там беды с этой кодировкой. Все сервера должны иметь кодировку UTF-8, а еще лучше установить ее по умолчанию в системе.

**Comment by SawFowl** [comment]
Я так же вижу ошибку которая появляется если команда выполняется вне основного потока, но на последней версии плагина ее не должно быть. Если конечно это не ошибка вашего ядра.

**Comment by AndryLavandery** [comment]
Прикольно, что на русском говорите.
Я попробую сменить ядро, поставить более новую версию плагина, если она, конечно, есть.

**Comment by AndryLavandery** [comment]
А кодировка вроде как стоит в консолях, я за этот флаг. Согласен за винду, но пока все настраиваю, будет там.

**Comment by SawFowl** [comment]
У винды всегда проблемы с этой кодировкой. Там вроде дефолтная cp886(не уверен на 100%). В Win 10 можно установить системную кодировку UTF-8, но там тогда в других местах беды появляются, текст не читается.
